---
title: "Deforestation"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(dygraphs)

options(scipen = 999)

forest <- read_csv("../Data/forest.csv")
forest_area <- read_csv("../Data/forest_area.csv")
brazil_loss <- read_csv("../Data/brazil_loss.csv")

forest_all <- forest %>%
  full_join(forest_area, by = c("entity","code","year"))
```

Global Deforestation
=======================================================================
Inputs {.sidebar}
-------------------------------------
Welcome to our flexdashboard! 

This dashboard is displaying information about deforestation. You'll notice there 
are two tabs - one for information about global deforestation, and the other is 
specific to Brazil. 

All data used for this dashboard comes from "Our World in Data," more specifically 
the "Forests and Deforestation" group of datasets curated by Hannah Ritchie and 
Max Roser. These datasets include information about the global distribution of 
forests, deforestation and forest losses, drivers of deforestation, data on the production of palm oil and soy, as well as data about afforestation or the gain 
of forest area. 

In our exploration of the data, we decided to highlight three different aspects. 
Our first element explores the distribution of global forest area and 
how that forest area has changed between 1990 and 2020. Our second group of plots 
dive deeper into this concept by illustrating the change in forest area experienced 
by three select countries (the United States, China, and Brazil) which can be compared.
Finally, our last plot, found on the second tab, illustrates the specific drivers 
of deforestation in Brazil across years and in a cumulative fashion. 

All elements of our dashboard are interactive - enjoy! 

References: 
Hannah Ritchie and Max Roser (2021) - "Forests and Deforestation". Published online at OurWorldInData.org. Retrieved from: 'https://ourworldindata.org/forests-and-deforestation' [Online Resource]


Row {data-height=485}
-----------------------------------------------------------------------

### Percent of Global Forest Area

```{r globe_percent}
globe_df <- forest_all %>% 
  filter(forest_all$entity != "World" & !is.na(forest_all$code)) %>% 
  rename(Percent = forest_area,
         Hectares = net_forest_conversion,
         Year = year)

percent_globe <- plot_geo() %>%
  add_trace(data = globe_df,
            z = ~Percent,
            text = globe_df$entity, 
            hovertemplate = "%{text}: %{z:.2r}%", 
            locations = globe_df$code,
            frame = ~Year,
            zauto = FALSE,
            zmax = 20,
            colors = "YlGn",
            name = "" # Remove Trace label
            ) %>%
  layout(geo = list(showocean = TRUE,
                    showland = TRUE,
                    showlakes = TRUE,
                    oceancolor = 'aliceblue',
                    landcolor = 'wheat',
                    lakecolor = 'lightskyblue1',
                    projection = list(type = "orthographic")),
         showlegend = TRUE)

percent_globe
```


### Net Change in Forest Area

```{r globe_net}
net_globe <- plot_geo() %>%
  add_trace(data = globe_df,
            z = ~ Hectares,
            text = globe_df$entity, 
            hovertemplate = "%{text}: %{z:.2s}",
            locations = globe_df$code,
            frame = ~Year,
            zauto = FALSE,
            zmax = 4000000,
            zmid = 0,
            zmin = -4000000,
            colors = "RdYlGn",
            name = "" # Remove Trace label
            ) %>%
  layout(geo = list(showocean = TRUE,
                    showland = TRUE,
                    showlakes = TRUE,
                    oceancolor = 'aliceblue',
                    landcolor = 'wheat',
                    lakecolor = 'lightskyblue1',
                    projection = list(type = "orthographic")),
         showlegend = TRUE)
         
net_globe
```

Row {data-height=515}
-----------------------------------------------------------------------

### Percentage of Global Forest Area

```{r usa}
usa <- forest_area %>%
  filter(code == "USA") %>%
  mutate(pct_change = (forest_area/lag(forest_area) - 1) * 100) %>% 
  rename(Year = year)

usa$forest_area <- round(usa$forest_area, 1)

usa_plot <- usa %>%
  plot_ly(
    domain = list(x = c(0, 1), y = c(0, 1)),
    value = ~forest_area,
    title = list(text = "U.S.:1990-2020"),
    frame = ~Year,
    type = "indicator",
    mode = "gauge+number",
    gauge = list(axis =list(range = list(NULL, 20)),
                 threshold = list(
                   line = list(color = "red", width = 4),
                   thickness = 0.75,
                   value = 7.1)))

usa_plot <- usa_plot %>%
  layout(margin = list(l=20,r=30))

usa_plot
```

### Percentage of Global Forest Area

```{r china}
chn <- forest_area %>%
  filter(code == "CHN") %>%
  mutate(pct_change = (forest_area/lag(forest_area) - 1) * 100)%>% 
  rename(Year = year)

chn$forest_area <- round(chn$forest_area, 1)

china_plot <- chn %>%
  plot_ly(
    domain = list(x = c(0, 1), y = c(0, 1)),
    value = ~forest_area,
    title = list(text = "China:1990-2020"),
    frame = ~Year,
    type = "indicator",
    mode = "gauge+number",
    gauge = list(axis =list(range = list(NULL, 20)),
                 threshold = list(
                   line = list(color = "red", width = 4),
                   thickness = 0.75,
                   value = 3.7)))

china_plot <- china_plot %>%
  layout(margin = list(l=20,r=30))

china_plot
```

### Percentage of Global Forest Area

```{r brazil}
bra <- forest_area %>%
  filter(code == "BRA") %>%
  mutate(pct_change = (forest_area/lag(forest_area) - 1) * 100) %>% 
  rename(Year = year)

bra$forest_area <- round(bra$forest_area, 1)

brazil_plot <- bra %>%
  plot_ly(
    domain = list(x = c(0, 1), y = c(0, 1)),
    value = ~forest_area,
    title = list(text = "Brazil:1990-2020"),
    frame = ~Year,
    type = "indicator",
    mode = "gauge+number",
    gauge = list(axis =list(range = list(NULL, 20)),
      threshold = list(
        line = list(color = "red", width = 4),
        thickness = 0.75,
        value = 13.9)))

brazil_plot <- brazil_plot %>%
  layout(margin = list(l=20,r=30))

brazil_plot
```

Brazil Deforestation
==========================================================================

```{r brazil_details}

brazil_loss %>% 
  mutate(Agriculture = (cumsum(commercial_crops + pasture + 
                                 tree_plantations_including_palm)/1000000), 
         Infrastructure = (cumsum(flooding_due_to_dams + 
                                    other_infrastructure + roads)/1000000), 
         Lumber = (cumsum(selective_logging + small_scale_clearing)/1000000), 
         Mining = (cumsum(mining)/1000000), 
         Fire = (cumsum(fire)/1000000), 
         `Natural Disturbances` = I(cumsum(natural_disturbances)/1000000)) %>% 
  select(year, Agriculture, Infrastructure, Lumber, Mining, Fire, 
         `Natural Disturbances`) %>% 
  dygraph(main = "Cumulative Deforestation by Industry - Brazil",
          x = "Year", 
          y = "Forest Area Lost (million Hectares)") %>% 
  dyRangeSelector() %>% 
  dyOptions(stackedGraph = TRUE) %>% 
  dyLegend(show = "follow")

```

